import { CardItem } from "../../src/1.domain/card/entities";
import { CardItemTypeProps } from "../../src/1.domain/card/vo";


describe("domain 레이어에 card와 관련된 단위테스트", () => {

  // 정합성에 사용할 card에 레이어 테스트
  type TestCase2Props = {
      item_id: string | undefined;
      card_id: string | undefined;
      type: CardItemTypeProps | undefined;
      x: number | undefined;
      y: number | undefined;
      width: number | undefined;
      height: number | undefined;
      rotation: number | undefined;
      scale_x: number | undefined;
      scale_y: number | undefined;
      opacity: number | undefined;
      z_index: number | undefined;
      is_locked: boolean | undefined;
      is_visible: boolean | undefined;
      name: string | undefined;
      option: Record<string, any> | undefined;
      created_at: Date;
      updated_at: Date;
      deleted_at: Date | undefined;
      ok : boolean;
  };

  const now = new Date();
  const TestCase2 : Array<TestCase2Props> = [
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: undefined,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '550e8400-e29b-41d4-a716-446655440000',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '      018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0     ',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: 'uuid',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: undefined,
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '       018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0     ',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '550e8400-e29b-41d4-a716-446655440000',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: "video",
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'image',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'Text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: '     text     ',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'another',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: undefined,
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 0,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: undefined,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 0,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: undefined,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 0,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: -1,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 0,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: undefined,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: undefined,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: -1,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: -1,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 0,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: -1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 0,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: -1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 0,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1.1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: -0.1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: -1,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: undefined,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: undefined,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: undefined,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: undefined,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: undefined,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: undefined,
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: Array(255).fill("n").join(""),
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: Array(256).fill("n").join(""),
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: undefined,
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    }
  ]
  test.each(TestCase2)("card_item에 정합성 테스트", ({
    item_id, card_id, type, x, y, width, height, rotation, scale_x, scale_y, opacity, z_index, is_locked, is_visible, name, option, created_at, updated_at, deleted_at, ok
  }) => {
    const test2 = () => {
      item_id = item_id as string;
      card_id = card_id as string;
      type = type as string;
      x = x as number;
      y = y as number;
      width = width as number;
      height = height;
      rotation = rotation as number;
      scale_x = scale_x as number;
      scale_y = scale_y as number;
      opacity = opacity;
      z_index = z_index;
      is_locked = is_locked;
      is_visible = is_visible;
      name = name;
      option = option as Record<string, any>;
      created_at = created_at;
      updated_at = updated_at;
      deleted_at = deleted_at;
      return new CardItem({
        item_id, card_id, type, x, y, width, height, rotation, scale_x, scale_y, opacity, z_index, is_locked, is_visible, name, option, created_at, updated_at, deleted_at
      });
    };
    if (ok) {
      const t2 = test2();
      expect(t2.getItemId()).toBe(item_id?.trim());
      expect(t2.getCardId()).toBe(card_id?.trim());
      expect(t2.getType()).toBe(type?.trim().toLowerCase());
      expect(t2.getX()).toBe(x);
      expect(t2.getY()).toBe(y);
      expect(t2.getWidth()).toBe(width);
      expect(t2.getHeight()).toBe(height);
      expect(t2.getRotation()).toBe(rotation);
      expect(t2.getScaleX()).toBe(scale_x);
      expect(t2.getScaleY()).toBe(scale_y);
      expect(t2.getOpacity()).toBe(opacity);
      expect(t2.getZindex()).toBe(z_index);
      expect(t2.getIsLocked()).toBe(is_locked);
      expect(t2.getIsVisible()).toBe(is_visible);
      expect(t2.getName()).toBe(name?.trim());
      expect(t2.getOption()).toEqual(option);
    } else expect(test2).toThrow();

  });

});