export type StackCategory =
  | 'ai'
  | 'backend'
  | 'database'
  | 'desktop'
  | 'devops'
  | 'frontend'
  | 'game'
  | 'hardware'
  | 'language'
  | 'mobile'
  | 'tool';

export interface StackIconInfo {
  id: string;
  name: string;
  src: string;
  category: StackCategory;
}

export const STACK_LIST: StackIconInfo[] = [
  // --- AI ---
  {
    id: 'pytorch',
    name: 'Pytorch',
    src: '/icons/stack/ai/pytorch.svg',
    category: 'ai',
  },
  {
    id: 'tensorflow',
    name: 'Tensorflow',
    src: '/icons/stack/ai/tensorflow.svg',
    category: 'ai',
  },

  // --- BACKEND ---
  {
    id: 'actix',
    name: 'Actix',
    src: '/icons/stack/backend/actix.svg',
    category: 'backend',
  },
  {
    id: 'adonis',
    name: 'Adonis',
    src: '/icons/stack/backend/adonis.svg',
    category: 'backend',
  },
  {
    id: 'apollo',
    name: 'Apollo',
    src: '/icons/stack/backend/apollo.svg',
    category: 'backend',
  },
  {
    id: 'deno',
    name: 'Deno',
    src: '/icons/stack/backend/deno.svg',
    category: 'backend',
  },
  {
    id: 'django',
    name: 'Django',
    src: '/icons/stack/backend/django.svg',
    category: 'backend',
  },
  {
    id: 'dotnet',
    name: 'Dotnet',
    src: '/icons/stack/backend/dotnet.svg',
    category: 'backend',
  },
  {
    id: 'expressjs',
    name: 'Expressjs',
    src: '/icons/stack/backend/expressjs.svg',
    category: 'backend',
  },
  {
    id: 'fastapi',
    name: 'Fastapi',
    src: '/icons/stack/backend/fastapi.svg',
    category: 'backend',
  },
  {
    id: 'flask',
    name: 'Flask',
    src: '/icons/stack/backend/flask.svg',
    category: 'backend',
  },
  {
    id: 'graphql',
    name: 'Graphql',
    src: '/icons/stack/backend/graphql.svg',
    category: 'backend',
  },
  {
    id: 'kafka',
    name: 'Kafka',
    src: '/icons/stack/backend/kafka.svg',
    category: 'backend',
  },
  {
    id: 'ktor',
    name: 'Ktor',
    src: '/icons/stack/backend/ktor.svg',
    category: 'backend',
  },
  {
    id: 'laravel',
    name: 'Laravel',
    src: '/icons/stack/backend/laravel.svg',
    category: 'backend',
  },
  {
    id: 'nestjs',
    name: 'Nestjs',
    src: '/icons/stack/backend/nestjs.svg',
    category: 'backend',
  },
  {
    id: 'nodejs',
    name: 'Nodejs',
    src: '/icons/stack/backend/nodejs.svg',
    category: 'backend',
  },
  {
    id: 'rabbitmq',
    name: 'Rabbitmq',
    src: '/icons/stack/backend/rabbitmq.svg',
    category: 'backend',
  },
  {
    id: 'rails',
    name: 'Rails',
    src: '/icons/stack/backend/rails.svg',
    category: 'backend',
  },
  {
    id: 'rocket',
    name: 'Rocket',
    src: '/icons/stack/backend/rocket.svg',
    category: 'backend',
  },
  {
    id: 'spring',
    name: 'Spring',
    src: '/icons/stack/backend/spring.svg',
    category: 'backend',
  },
  {
    id: 'symfony',
    name: 'Symfony',
    src: '/icons/stack/backend/symfony.svg',
    category: 'backend',
  },
  {
    id: 'wordpress',
    name: 'Wordpress',
    src: '/icons/stack/backend/wordpress.svg',
    category: 'backend',
  },

  // --- DATABASE ---
  {
    id: 'appwrite',
    name: 'Appwrite',
    src: '/icons/stack/database/appwrite.svg',
    category: 'database',
  },
  {
    id: 'cassandra',
    name: 'Cassandra',
    src: '/icons/stack/database/cassandra.svg',
    category: 'database',
  },
  {
    id: 'dynamodb',
    name: 'Dynamodb',
    src: '/icons/stack/database/dynamodb.svg',
    category: 'database',
  },
  {
    id: 'firebase',
    name: 'Firebase',
    src: '/icons/stack/database/firebase.svg',
    category: 'database',
  },
  {
    id: 'hibernate',
    name: 'Hibernate',
    src: '/icons/stack/database/hibernate.svg',
    category: 'database',
  },
  {
    id: 'mongodb',
    name: 'Mongodb',
    src: '/icons/stack/database/mongodb.svg',
    category: 'database',
  },
  {
    id: 'mysql',
    name: 'Mysql',
    src: '/icons/stack/database/mysql.svg',
    category: 'database',
  },
  {
    id: 'planetscale',
    name: 'Planetscale',
    src: '/icons/stack/database/planetscale.svg',
    category: 'database',
  },
  {
    id: 'postgresql',
    name: 'Postgresql',
    src: '/icons/stack/database/postgresql.svg',
    category: 'database',
  },
  {
    id: 'prisma',
    name: 'Prisma',
    src: '/icons/stack/database/prisma.svg',
    category: 'database',
  },
  {
    id: 'redis',
    name: 'Redis',
    src: '/icons/stack/database/redis.svg',
    category: 'database',
  },
  {
    id: 'sequelize',
    name: 'Sequelize',
    src: '/icons/stack/database/sequelize.svg',
    category: 'database',
  },
  {
    id: 'sqlite',
    name: 'Sqlite',
    src: '/icons/stack/database/sqlite.svg',
    category: 'database',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    src: '/icons/stack/database/supabase.svg',
    category: 'database',
  },

  // --- DESKTOP ---
  {
    id: 'electron',
    name: 'Electron',
    src: '/icons/stack/desktop/electron.svg',
    category: 'desktop',
  },
  {
    id: 'qt',
    name: 'Qt',
    src: '/icons/stack/desktop/qt.svg',
    category: 'desktop',
  },
  {
    id: 'tauri',
    name: 'Tauri',
    src: '/icons/stack/desktop/tauri.svg',
    category: 'desktop',
  },

  // --- DEVOPS ---
  {
    id: 'ansible',
    name: 'Ansible',
    src: '/icons/stack/devops/ansible.svg',
    category: 'devops',
  },
  {
    id: 'aws',
    name: 'Aws',
    src: '/icons/stack/devops/aws.svg',
    category: 'devops',
  },
  {
    id: 'azure',
    name: 'Azure',
    src: '/icons/stack/devops/azure.svg',
    category: 'devops',
  },
  {
    id: 'bash',
    name: 'Bash',
    src: '/icons/stack/devops/bash.svg',
    category: 'devops',
  },
  {
    id: 'cilium',
    name: 'Cilium',
    src: '/icons/stack/devops/cilium.svg',
    category: 'devops',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    src: '/icons/stack/devops/cloudflare.svg',
    category: 'devops',
  },
  {
    id: 'cmake',
    name: 'Cmake',
    src: '/icons/stack/devops/cmake.svg',
    category: 'devops',
  },
  {
    id: 'containerd',
    name: 'Containerd',
    src: '/icons/stack/devops/container_d.svg',
    category: 'devops',
  },
  {
    id: 'docker',
    name: 'Docker',
    src: '/icons/stack/devops/docker.svg',
    category: 'devops',
  },
  {
    id: 'gcp',
    name: 'Gcp',
    src: '/icons/stack/devops/gcp.svg',
    category: 'devops',
  },
  {
    id: 'githubactions',
    name: 'Githubactions',
    src: '/icons/stack/devops/githubactions.svg',
    category: 'devops',
  },
  {
    id: 'gitlab',
    name: 'Gitlab',
    src: '/icons/stack/devops/gitlab.svg',
    category: 'devops',
  },
  {
    id: 'gradle',
    name: 'Gradle',
    src: '/icons/stack/devops/gradle.svg',
    category: 'devops',
  },
  {
    id: 'grafana',
    name: 'Grafana',
    src: '/icons/stack/devops/grafana.svg',
    category: 'devops',
  },
  {
    id: 'heroku',
    name: 'Heroku',
    src: '/icons/stack/devops/heroku.svg',
    category: 'devops',
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    src: '/icons/stack/devops/jenkins.svg',
    category: 'devops',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    src: '/icons/stack/devops/kubernetes.svg',
    category: 'devops',
  },
  {
    id: 'linux',
    name: 'Linux',
    src: '/icons/stack/devops/linux.svg',
    category: 'devops',
  },
  {
    id: 'maven',
    name: 'Maven',
    src: '/icons/stack/devops/maven.svg',
    category: 'devops',
  },
  {
    id: 'ncp',
    name: 'NCP',
    src: '/icons/stack/devops/ncp.svg',
    category: 'devops',
  },
  {
    id: 'netlify',
    name: 'Netlify',
    src: '/icons/stack/devops/netlify.svg',
    category: 'devops',
  },
  {
    id: 'nginx',
    name: 'Nginx',
    src: '/icons/stack/devops/nginx.svg',
    category: 'devops',
  },
  {
    id: 'openshift',
    name: 'Openshift',
    src: '/icons/stack/devops/openshift.svg',
    category: 'devops',
  },
  {
    id: 'openstack',
    name: 'Openstack',
    src: '/icons/stack/devops/openstack.svg',
    category: 'devops',
  },
  {
    id: 'plan9',
    name: 'Plan9',
    src: '/icons/stack/devops/plan9.svg',
    category: 'devops',
  },
  {
    id: 'powershell',
    name: 'Powershell',
    src: '/icons/stack/devops/powershell.svg',
    category: 'devops',
  },
  {
    id: 'prometheus',
    name: 'Prometheus',
    src: '/icons/stack/devops/prometheus.svg',
    category: 'devops',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    src: '/icons/stack/devops/vercel.svg',
    category: 'devops',
  },
  {
    id: 'workers',
    name: 'Workers',
    src: '/icons/stack/devops/workers.svg',
    category: 'devops',
  },

  // --- FRONTEND ---
  {
    id: 'alpinejs',
    name: 'Alpinejs',
    src: '/icons/stack/frontend/alpinejs.svg',
    category: 'frontend',
  },
  {
    id: 'angular',
    name: 'Angular',
    src: '/icons/stack/frontend/angular.svg',
    category: 'frontend',
  },
  {
    id: 'astro',
    name: 'Astro',
    src: '/icons/stack/frontend/astro.svg',
    category: 'frontend',
  },
  {
    id: 'babel',
    name: 'Babel',
    src: '/icons/stack/frontend/babel.svg',
    category: 'frontend',
  },
  {
    id: 'bootstrap',
    name: 'Bootstrap',
    src: '/icons/stack/frontend/bootstrap.svg',
    category: 'frontend',
  },
  {
    id: 'css',
    name: 'Css',
    src: '/icons/stack/frontend/css.svg',
    category: 'frontend',
  },
  {
    id: 'd3',
    name: 'D3',
    src: '/icons/stack/frontend/d3.svg',
    category: 'frontend',
  },
  {
    id: 'ember',
    name: 'Ember',
    src: '/icons/stack/frontend/ember.svg',
    category: 'frontend',
  },
  {
    id: 'emotion',
    name: 'Emotion',
    src: '/icons/stack/frontend/emotion.svg',
    category: 'frontend',
  },
  {
    id: 'gatsby',
    name: 'Gatsby',
    src: '/icons/stack/frontend/gatsby.svg',
    category: 'frontend',
  },
  {
    id: 'gulp',
    name: 'Gulp',
    src: '/icons/stack/frontend/gulp.svg',
    category: 'frontend',
  },
  {
    id: 'jquery',
    name: 'Jquery',
    src: '/icons/stack/frontend/jquery.svg',
    category: 'frontend',
  },
  {
    id: 'lit',
    name: 'Lit',
    src: '/icons/stack/frontend/lit.svg',
    category: 'frontend',
  },
  {
    id: 'materialui',
    name: 'Materialui',
    src: '/icons/stack/frontend/materialui.svg',
    category: 'frontend',
  },
  {
    id: 'nextjs',
    name: 'Nextjs',
    src: '/icons/stack/frontend/nextjs.svg',
    category: 'frontend',
  },
  {
    id: 'nuxtjs',
    name: 'Nuxtjs',
    src: '/icons/stack/frontend/nuxtjs.svg',
    category: 'frontend',
  },
  {
    id: 'pug',
    name: 'Pug',
    src: '/icons/stack/frontend/pug.svg',
    category: 'frontend',
  },
  {
    id: 'react',
    name: 'React',
    src: '/icons/stack/frontend/react.svg',
    category: 'frontend',
  },
  {
    id: 'reactivex',
    name: 'Reactivex',
    src: '/icons/stack/frontend/reactivex.svg',
    category: 'frontend',
  },
  {
    id: 'redux',
    name: 'Redux',
    src: '/icons/stack/frontend/redux.svg',
    category: 'frontend',
  },
  {
    id: 'remix',
    name: 'Remix',
    src: '/icons/stack/frontend/remix.svg',
    category: 'frontend',
  },
  {
    id: 'rollupjs',
    name: 'Rollupjs',
    src: '/icons/stack/frontend/rollupjs.svg',
    category: 'frontend',
  },
  {
    id: 'sass',
    name: 'Sass',
    src: '/icons/stack/frontend/sass.svg',
    category: 'frontend',
  },
  {
    id: 'solidjs',
    name: 'Solidjs',
    src: '/icons/stack/frontend/solidjs.svg',
    category: 'frontend',
  },
  {
    id: 'styledcomponents',
    name: 'Styledcomponents',
    src: '/icons/stack/frontend/styledcomponents.svg',
    category: 'frontend',
  },
  {
    id: 'svelte',
    name: 'Svelte',
    src: '/icons/stack/frontend/svelte.svg',
    category: 'frontend',
  },
  {
    id: 'svg',
    name: 'Svg',
    src: '/icons/stack/frontend/svg.svg',
    category: 'frontend',
  },
  {
    id: 'tailwindcss',
    name: 'Tailwindcss',
    src: '/icons/stack/frontend/tailwindcss.svg',
    category: 'frontend',
  },
  {
    id: 'threejs',
    name: 'Threejs',
    src: '/icons/stack/frontend/threejs.svg',
    category: 'frontend',
  },
  {
    id: 'vite',
    name: 'Vite',
    src: '/icons/stack/frontend/vite.svg',
    category: 'frontend',
  },
  {
    id: 'vuejs',
    name: 'Vuejs',
    src: '/icons/stack/frontend/vuejs.svg',
    category: 'frontend',
  },
  {
    id: 'webflow',
    name: 'Webflow',
    src: '/icons/stack/frontend/webflow.svg',
    category: 'frontend',
  },
  {
    id: 'webpack',
    name: 'Webpack',
    src: '/icons/stack/frontend/webpack.svg',
    category: 'frontend',
  },
  {
    id: 'windicss',
    name: 'Windicss',
    src: '/icons/stack/frontend/windicss.svg',
    category: 'frontend',
  },

  // --- GAME ---
  {
    id: 'bevy',
    name: 'Bevy',
    src: '/icons/stack/game/bevy.svg',
    category: 'game',
  },
  {
    id: 'gamemakerstudio',
    name: 'Gamemakerstudio',
    src: '/icons/stack/game/gamemakerstudio.svg',
    category: 'game',
  },
  {
    id: 'godot',
    name: 'Godot',
    src: '/icons/stack/game/godot.svg',
    category: 'game',
  },
  {
    id: 'haxe',
    name: 'Haxe',
    src: '/icons/stack/game/haxe.svg',
    category: 'game',
  },
  {
    id: 'haxeflixel',
    name: 'Haxeflixel',
    src: '/icons/stack/game/haxeflixel.svg',
    category: 'game',
  },
  {
    id: 'unity',
    name: 'Unity',
    src: '/icons/stack/game/unity.svg',
    category: 'game',
  },
  {
    id: 'unrealengine',
    name: 'Unrealengine',
    src: '/icons/stack/game/unrealengine.svg',
    category: 'game',
  },

  // --- HARDWARE ---
  {
    id: 'arduino',
    name: 'Arduino',
    src: '/icons/stack/hardware/arduino.svg',
    category: 'hardware',
  },
  {
    id: 'raspberrypi',
    name: 'Raspberrypi',
    src: '/icons/stack/hardware/raspberrypi.svg',
    category: 'hardware',
  },
  {
    id: 'ros',
    name: 'Ros',
    src: '/icons/stack/hardware/ros.svg',
    category: 'hardware',
  },

  // --- LANGUAGE ---
  {
    id: 'aiscript',
    name: 'Aiscript',
    src: '/icons/stack/language/aiscript.svg',
    category: 'language',
  },
  {
    id: 'c',
    name: 'C',
    src: '/icons/stack/language/c.svg',
    category: 'language',
  },
  {
    id: 'clojure',
    name: 'Clojure',
    src: '/icons/stack/language/clojure.svg',
    category: 'language',
  },
  {
    id: 'coffeescript',
    name: 'Coffeescript',
    src: '/icons/stack/language/coffeescript.svg',
    category: 'language',
  },
  {
    id: 'cpp',
    name: 'Cpp',
    src: '/icons/stack/language/cpp.svg',
    category: 'language',
  },
  {
    id: 'crystal',
    name: 'Crystal',
    src: '/icons/stack/language/crystal.svg',
    category: 'language',
  },
  {
    id: 'cs',
    name: 'Cs',
    src: '/icons/stack/language/cs.svg',
    category: 'language',
  },
  {
    id: 'dart',
    name: 'Dart',
    src: '/icons/stack/language/dart.svg',
    category: 'language',
  },
  {
    id: 'elixir',
    name: 'Elixir',
    src: '/icons/stack/language/elixir.svg',
    category: 'language',
  },
  {
    id: 'forth',
    name: 'Forth',
    src: '/icons/stack/language/forth.svg',
    category: 'language',
  },
  {
    id: 'fortran',
    name: 'Fortran',
    src: '/icons/stack/language/fortran.svg',
    category: 'language',
  },
  {
    id: 'gherkin',
    name: 'Gherkin',
    src: '/icons/stack/language/gherkin.svg',
    category: 'language',
  },
  {
    id: 'golang',
    name: 'Golang',
    src: '/icons/stack/language/golang.svg',
    category: 'language',
  },
  {
    id: 'haskell',
    name: 'Haskell',
    src: '/icons/stack/language/haskell.svg',
    category: 'language',
  },
  {
    id: 'html',
    name: 'Html',
    src: '/icons/stack/language/html.svg',
    category: 'language',
  },
  {
    id: 'java',
    name: 'Java',
    src: '/icons/stack/language/java.svg',
    category: 'language',
  },
  {
    id: 'javascript',
    name: 'Javascript',
    src: '/icons/stack/language/javascript.svg',
    category: 'language',
  },
  {
    id: 'julia',
    name: 'Julia',
    src: '/icons/stack/language/julia.svg',
    category: 'language',
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    src: '/icons/stack/language/kotlin.svg',
    category: 'language',
  },
  {
    id: 'latex',
    name: 'Latex',
    src: '/icons/stack/language/latex.svg',
    category: 'language',
  },
  {
    id: 'lua',
    name: 'Lua',
    src: '/icons/stack/language/lua.svg',
    category: 'language',
  },
  {
    id: 'markdown',
    name: 'Markdown',
    src: '/icons/stack/language/markdown.svg',
    category: 'language',
  },
  {
    id: 'matlab',
    name: 'Matlab',
    src: '/icons/stack/language/matlab.svg',
    category: 'language',
  },
  {
    id: 'nim',
    name: 'Nim',
    src: '/icons/stack/language/nim.svg',
    category: 'language',
  },
  {
    id: 'ocaml',
    name: 'Ocaml',
    src: '/icons/stack/language/ocaml.svg',
    category: 'language',
  },
  {
    id: 'perl',
    name: 'Perl',
    src: '/icons/stack/language/perl.svg',
    category: 'language',
  },
  {
    id: 'php',
    name: 'Php',
    src: '/icons/stack/language/php.svg',
    category: 'language',
  },
  {
    id: 'python',
    name: 'Python',
    src: '/icons/stack/language/python.svg',
    category: 'language',
  },
  {
    id: 'r',
    name: 'R',
    src: '/icons/stack/language/r.svg',
    category: 'language',
  },
  {
    id: 'regex',
    name: 'Regex',
    src: '/icons/stack/language/regex.svg',
    category: 'language',
  },
  {
    id: 'ruby',
    name: 'Ruby',
    src: '/icons/stack/language/ruby.svg',
    category: 'language',
  },
  {
    id: 'rust',
    name: 'Rust',
    src: '/icons/stack/language/rust.svg',
    category: 'language',
  },
  {
    id: 'scala',
    name: 'Scala',
    src: '/icons/stack/language/scala.svg',
    category: 'language',
  },
  {
    id: 'swift',
    name: 'Swift',
    src: '/icons/stack/language/swift.svg',
    category: 'language',
  },
  {
    id: 'typescript',
    name: 'Typescript',
    src: '/icons/stack/language/typescript.svg',
    category: 'language',
  },
  {
    id: 'v',
    name: 'V',
    src: '/icons/stack/language/v.svg',
    category: 'language',
  },
  {
    id: 'vala',
    name: 'Vala',
    src: '/icons/stack/language/vala.svg',
    category: 'language',
  },
  {
    id: 'webassembly',
    name: 'Webassembly',
    src: '/icons/stack/language/webassembly.svg',
    category: 'language',
  },
  {
    id: 'zig',
    name: 'Zig',
    src: '/icons/stack/language/zig.svg',
    category: 'language',
  },

  // --- MOBILE ---
  {
    id: 'androidstudio',
    name: 'Androidstudio',
    src: '/icons/stack/mobile/androidstudio.svg',
    category: 'mobile',
  },
  {
    id: 'flutter',
    name: 'Flutter',
    src: '/icons/stack/mobile/flutter.svg',
    category: 'mobile',
  },

  // --- TOOL ---
  {
    id: 'ableton',
    name: 'Ableton',
    src: '/icons/stack/tool/ableton.svg',
    category: 'tool',
  },
  {
    id: 'activitypub',
    name: 'Activitypub',
    src: '/icons/stack/tool/activitypub.svg',
    category: 'tool',
  },
  {
    id: 'aftereffects',
    name: 'Aftereffects',
    src: '/icons/stack/tool/aftereffects.svg',
    category: 'tool',
  },
  {
    id: 'argo',
    name: 'Argo',
    src: '/icons/stack/tool/argo.svg',
    category: 'tool',
  },
  {
    id: 'atom',
    name: 'Atom',
    src: '/icons/stack/tool/atom.svg',
    category: 'tool',
  },
  {
    id: 'audition',
    name: 'Audition',
    src: '/icons/stack/tool/audition.svg',
    category: 'tool',
  },
  {
    id: 'autocad',
    name: 'Autocad',
    src: '/icons/stack/tool/autocad.svg',
    category: 'tool',
  },
  {
    id: 'blender',
    name: 'Blender',
    src: '/icons/stack/tool/blender.svg',
    category: 'tool',
  },
  {
    id: 'codepen',
    name: 'Codepen',
    src: '/icons/stack/tool/codepen.svg',
    category: 'tool',
  },
  {
    id: 'devto',
    name: 'Devto',
    src: '/icons/stack/tool/devto.svg',
    category: 'tool',
  },
  {
    id: 'discord',
    name: 'Discord',
    src: '/icons/stack/tool/discord.svg',
    category: 'tool',
  },
  {
    id: 'discordbots',
    name: 'Discordbots',
    src: '/icons/stack/tool/discordbots.svg',
    category: 'tool',
  },
  {
    id: 'eclipse',
    name: 'Eclipse',
    src: '/icons/stack/tool/eclipse.svg',
    category: 'tool',
  },
  {
    id: 'emacs',
    name: 'Emacs',
    src: '/icons/stack/tool/emacs.svg',
    category: 'tool',
  },
  {
    id: 'fediverse',
    name: 'Fediverse',
    src: '/icons/stack/tool/fediverse.svg',
    category: 'tool',
  },
  {
    id: 'figma',
    name: 'Figma',
    src: '/icons/stack/tool/figma.svg',
    category: 'tool',
  },
  {
    id: 'git',
    name: 'Git',
    src: '/icons/stack/tool/git.svg',
    category: 'tool',
  },
  {
    id: 'github',
    name: 'Github',
    src: '/icons/stack/tool/github.svg',
    category: 'tool',
  },
  {
    id: 'idea',
    name: 'Idea',
    src: '/icons/stack/tool/idea.svg',
    category: 'tool',
  },
  {
    id: 'illustrator',
    name: 'Illustrator',
    src: '/icons/stack/tool/illustrator.svg',
    category: 'tool',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    src: '/icons/stack/tool/instagram.svg',
    category: 'tool',
  },
  {
    id: 'ipfs',
    name: 'Ipfs',
    src: '/icons/stack/tool/ipfs.svg',
    category: 'tool',
  },
  {
    id: 'jest',
    name: 'Jest',
    src: '/icons/stack/tool/jest.svg',
    category: 'tool',
  },
  {
    id: 'lightroom',
    name: 'Lightroom',
    src: '/icons/stack/tool/lightroom.svg',
    category: 'tool',
  },
  {
    id: 'linkedin',
    name: 'Linkedin',
    src: '/icons/stack/tool/linkedin.svg',
    category: 'tool',
  },
  {
    id: 'mastodon',
    name: 'Mastodon',
    src: '/icons/stack/tool/mastodon.svg',
    category: 'tool',
  },
  {
    id: 'misskey',
    name: 'Misskey',
    src: '/icons/stack/tool/misskey.svg',
    category: 'tool',
  },
  {
    id: 'neovim',
    name: 'Neovim',
    src: '/icons/stack/tool/neovim.svg',
    category: 'tool',
  },
  {
    id: 'photoshop',
    name: 'Photoshop',
    src: '/icons/stack/tool/photoshop.svg',
    category: 'tool',
  },
  {
    id: 'postman',
    name: 'Postman',
    src: '/icons/stack/tool/postman.svg',
    category: 'tool',
  },
  {
    id: 'premiere',
    name: 'Premiere',
    src: '/icons/stack/tool/premiere.svg',
    category: 'tool',
  },
  {
    id: 'replit',
    name: 'Replit',
    src: '/icons/stack/tool/replit.svg',
    category: 'tool',
  },
  {
    id: 'selenium',
    name: 'Selenium',
    src: '/icons/stack/tool/selenium.svg',
    category: 'tool',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    src: '/icons/stack/tool/sentry.svg',
    category: 'tool',
  },
  {
    id: 'sketchup',
    name: 'Sketchup',
    src: '/icons/stack/tool/sketchup.svg',
    category: 'tool',
  },
  {
    id: 'solidity',
    name: 'Solidity',
    src: '/icons/stack/tool/solidity.svg',
    category: 'tool',
  },
  {
    id: 'stackoverflow',
    name: 'Stackoverflow',
    src: '/icons/stack/tool/stackoverflow.svg',
    category: 'tool',
  },
  {
    id: 'twitter',
    name: 'Twitter',
    src: '/icons/stack/tool/twitter.svg',
    category: 'tool',
  },
  {
    id: 'vim',
    name: 'Vim',
    src: '/icons/stack/tool/vim.svg',
    category: 'tool',
  },
  {
    id: 'visualstudio',
    name: 'Visualstudio',
    src: '/icons/stack/tool/visualstudio.svg',
    category: 'tool',
  },
  {
    id: 'vscode',
    name: 'Vscode',
    src: '/icons/stack/tool/vscode.svg',
    category: 'tool',
  },
  { id: 'xd', name: 'Xd', src: '/icons/stack/tool/xd.svg', category: 'tool' },
];
